### ISSUE TITLE
180版本，华为mate20p，每次指纹解锁，app都会自动弹出来

### ISSUE THREAD

**Issue by zzy302** [zfdang/Android-Touch-Helper#1]
提示，正在根据关键字跳过广告

**Comment by zzy302** [comment]
大概步骤：
1、手机亮屏，打开app
2、回到桌面
3、关闭屏幕
4、通过屏幕指纹解锁
5、app自动弹出来
191版本也有类似问题，还挺严重的。。

**Comment by zfdang** [comment]
把桌面app加到白名单里试试看

**Comment by zfdang** [comment]
这个的原因是，把桌面 app当成了一个普通应用，然后在里面找“跳过”字样，找到了这个“开屏跳过”app的图标，于是自动点击了...

**Comment by zzy302** [comment]
> 这个的原因是，把桌面 app当成了一个普通应用，然后在里面找“跳过”字样，找到了这个“开屏跳过”app的图标，于是自动点击了...

我之前还特意看下，白名单的程序列表里面没有“华为桌面”或者相关类似的应用，系统自带的应用都加到白名单了，启用的app都是第三方安装的

导致这个现象的原因分析比较靠谱

**Comment by zfdang** [comment]
你用“设置”-》“高级设置”-》“添加程序的跳过方法”，然后退回到桌面，点击”显示控件“， 看看桌面是那个app，然后看看这个app在不在白名单里吧

**Comment by zzy302** [comment]
> 你用“设置”-》“高级设置”-》“添加程序的跳过方法”，然后退回到桌面，点击”显示控件“， 看看桌面是那个app，然后看看这个app在不在白名单里吧

排除法试了下，就是拼多多app的锅。。把pdd加入白名单，开机正常；把pdd移出白名单，开机必现。。（自动弹出本app）
pdd这个也是够流氓的啊。。

**Comment by TimoLin** [comment]
OnePlus 8 也遇到了这个问题，App版本2022.02.15(222)，没有安装拼多多。

> 你用“设置”-》“高级设置”-》“添加程序的跳过方法”，然后退回到桌面，点击”显示控件“， 看看桌面是那个app，然后看看这个app在不在白名单里吧
```
包名:  net.oneplus.launcher
活动:  net.oneplus.launcher.Launcher
```
> 把桌面app加到白名单里试试看

在应用程序白名单中没有找到相关的应用。

> 这个的原因是，把桌面 app当成了一个普通应用，然后在里面找“跳过”字样，找到了这个“开屏跳过”app的图标，于是自动点击了...

确实是这个的原因。把“开屏跳过” app图标从桌面上移除后，该问题不再出现。
