### ISSUE TITLE
魅族16.经常严重卡顿

### ISSUE THREAD

**Issue by sunqianGitHub** [zfdang/Android-Touch-Helper#10]
魅族16S，发现有时候打开App一顿胡乱点击，比如都点击到拍照和系统设置里面了，然后就长时间系统界面无响应。等很久才能恢复。

问下默认关键字是只检查启动第一屏？还是其他的界面也会检测？

我能不能设置不检查关键字，单独通过添加控件来跳过，这样应该是会好很多

**Comment by zfdang** [comment]
一个程序，只有在启动之后的4秒钟之内，才会去检查和跳过广告。我有的时候也会发现误点击的时候，但是都是发现了跳过关键字的时候，这时候等几秒钟，就不会再监测，也不会乱点击了

要是实在不行，就把这个app加入到白名单里吧

**Comment by sunqianGitHub** [comment]
我尝试改为2秒钟，还是误操作。

能不能开个关键词的设置，这样高级玩家完全可以每个App都自定义跳过，发现这个自定义非常好用

或者跳过关键词在哪个位置呢？我能否自己编译一个版本？

**Comment by zfdang** [comment]
你看看这个说明：

https://touchhelper.zfdang.com/settings

**Comment by sunqianGitHub** [comment]
重新描述下：我想彻底不用关键词查找功能，只用自定义的控件。（看起来关键词查找优先级最高，其次才是控件查找？）现在发现删除了关键词设置栏里面的“跳过”二字，打开App后还是误点击很多
