### ISSUE TITLE
可否将 b_method_by_button_keyword 变量恒为false 编译一个版本吗？

### ISSUE THREAD

**Issue by sunqianGitHub** [zfdang/Android-Touch-Helper#11]
可否将 b_method_by_button_keyword 变量恒为false 编译一个版本吗？
目的是想要一个没有关键字点击的版本。

请问这个代码需要如何编译呢？

能否帮忙编译一个

**Comment by zfdang** [comment]
这个有自动编译脚本的啊，你fork一个repo，改这行代码，应该就会自动编译个apk出来了
