### ISSUE TITLE
建议加个在最近任务中隐藏和常置前台

### ISSUE THREAD

**Issue by zerojade** [zfdang/Android-Touch-Helper#22]
如题。另tx视频的跳过控件那个高级方法不好使。

**Comment by zfdang** [comment]
任务中隐藏不隐藏没有意义，任务中的那个程序可以直接关闭，也不影响后台的正常工作。
tx视频确实比较流浪，跳过是一个不知道什么东西做的，不是按钮，也不是文本，所以通过添加控件的方式就不能对付；但是可以通过添加位置的方式来跳过，你试试看
