### ISSUE TITLE
知乎等软件打开状态下，息屏后再次亮屏出现广告无法去除

### ISSUE THREAD

**Issue by CMingXiang** [zfdang/Android-Touch-Helper#28]
问题描述： 你好，我在使用知乎软件时，在打开知乎，浏览内容后长时间不操作，手机息屏，在再次拿起人脸识别后，打开手机后，知乎出现开屏广告，无法识别，自动跳过。
      希望作者能优化解决一下，非常感谢！

**Comment by zfdang** [comment]
新版应该解决这个问题了
