### ISSUE TITLE
感谢，每次指纹解锁后【开屏跳过】应用主窗口都自动弹到最前

### ISSUE THREAD

**Issue by lly277365** [zfdang/Android-Touch-Helper#32]
软件非常好用，感谢大佬的工作和开源！

遇到一个问题，手机关机后，在每次指纹解锁手机后【开屏跳过】应用主窗口都自动弹到最前，我使用的版本是2022.02.15(222)。

最后再次感谢作者的无私付出！

**Comment by zfdang** [comment]
改了一下，把本软件给hardcode排除了一下，试试新版吧
