### ISSUE TITLE
那个辅助触控怎么隐藏

### ISSUE THREAD

**Issue by WeihuaGu** [zfdang/Android-Touch-Helper#33]
我有强迫症

**Comment by zfdang** [comment]
什么意思？你用的是什么手机？

**Comment by WeihuaGu** [comment]
![Screenshot_20220402-112223_GitHub.png](https://user-images.githubusercontent.com/11705342/161364030-92825248-0aef-455b-9667-51ee19865266.png)

**Comment by WeihuaGu** [comment]
就是这个手的触控 设置里没找见怎么隐藏

**Comment by zfdang** [comment]
之前用小米，没有这个图标，现在用vivo, 也没有这个图标，三星也没有。跟你的手机系统有关系

**Comment by WeihuaGu** [comment]
@zfdang 这应该跟系统没关系吧
我用的小米手机刷的pixel experience,就是原生安卓12的系统

**Comment by zfdang** [comment]
这个显然就是系统的行为啊，跟应用没关系

**Comment by zfdang** [comment]
你看看这个能不能解决：

https://support.google.com/pixelphone/thread/132760199/mistry-floating-button

**Comment by zfdang** [comment]
Go to Settings->Accessibility->Text and display->Color correction, and turn off "Color correction shortcut". This will remove the floating icon. Let me know if you need more help.

类似的，把开屏跳过下面的shortcut关闭了，应该就是没了

**Comment by WeihuaGu** [comment]
感谢 无知了😅
