### ISSUE TITLE
华为 重启后 无障碍设置 识别失败

### ISSUE THREAD

**Issue by HoffmanZheng** [zfdang/Android-Touch-Helper#43]
华为 P30 系统为非鸿蒙 EMUI 11.0.0.155 
已经在无障碍服务里 enable 了开屏跳过（图2），但是在 app 中对无障碍的设置判断仍然是没有打开（图1）
导致应用的功能无法正常运作（之前刚安装的时候是可以用的，重启了下就这样了）
![image](https://user-images.githubusercontent.com/45369893/202965400-414cc3c3-c78f-4514-979d-977d9c2c0f36.png)
![image](https://user-images.githubusercontent.com/45369893/202965405-b6ddaf86-490c-4171-a00b-d9402d7fdadd.png)

**Comment by U5ER-N4ME** [comment]
之前用过别的同类型软件，也是使用无障碍服务进行跳过，同样也是重启或者莫名其妙不知道什么原因就提示没有打开无障碍了（此时系统仍显示已开启，与本issue相同）。解决方式可能是任务栏常驻和桌面小组件等方法。

**Comment by zfdang** [comment]
电源设置里再设置一下，这个跟各个系统自己的处理方法有很大关系:

看看这个吧：

https://touchhelper.zfdang.com/enable
