### ISSUE TITLE
在一加13.1下, 非play的开屏跳过无法启用无障碍服务

### ISSUE THREAD

**Issue by hshh** [zfdang/Android-Touch-Helper#61]
google play版没有问题, 但是版本比较老, 能否更新下play的版本.

非play版本提示, 受限制的设置. 出于安全考虑, 此设置目前不可用.

问题类似: https://zhuanlan.zhihu.com/p/512335294

**Comment by hshh** [comment]
有些系统可以在应用设置里面允许app打开访问受限制权限, 一加的开屏跳过没有.

目前可以用app ops将受限制权限设置为一直显示, 并且对开屏跳过启用, 就可以设置无障碍服务了.

**Comment by alex3236** [comment]
现在无障碍那里点一次 提示不可用之后，从 **桌面** 进入设置app找应用信息 右上角就有三个点“允许访问受限制权限”了
