### ISSUE TITLE
我这边将继续基于本项目进行完善功能,欢迎大家一起来维护

### ISSUE THREAD

**Issue by clbDream** [zfdang/Android-Touch-Helper#91]
我这边平时时间比较多,将基于本项目继续开发维护,欢迎大家一起来完善这个项目
项目地址:[Pdlbox-Ad-Jump](https://github.com/clbDream/Pdlbox-Ad-Jump)

**Comment by zfdang** [comment]
你需要的话，我可以把你加到这个项目的collaborator里，就可以在这里直接改了

**Comment by clbDream** [comment]
可以呀?我看这个很久没有提交代码了,以为不维护了
